linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - godot
    - gofumpt
    - makezero
    - nakedret
    - nestif
    - noctx
    - predeclared
linters-settings:
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 20
  exhaustive:
    default-signifies-exhaustive: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocognit
        - goconst
        - unused
        - bodyclose
