apiVersion: v1
kind: Service
metadata:
  name: nwctl-aggregator
spec:
  type: ClusterIP
  selector:
    app: nwctl-aggregator
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
