apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuesta-aggregator
spec:
  selector:
    matchLabels:
      app: kuesta-aggregator
  replicas: 1
  template:
    metadata:
      labels:
        app: kuesta-aggregator
    spec:
      containers:
        - name: kuesta
          image: kuesta:latest
          command:
            - /bin/kuesta
          args:
            - device
            - aggregate
          env:
            - name: KUESTA_DEVEL
              value: "true"
            - name: KUESTA_VERBOSE
              value: "2"
            - name: KUESTA_STATUS_ROOT_PATH
              value: /data/repo_status
            - name: KUESTA_STATUS_REPO_URL
              value: https://path/to/repo-status
            - name: KUESTA_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuesta-secrets
                  key: gitToken
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /data
              name: kuesta-aggregator-data
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
      volumes:
        - name: kuesta-aggregator-data
          persistentVolumeClaim:
            claimName: kuesta-aggregator-data
