# permissions for end users to view devicerollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicerollout-viewer-role
rules:
- apiGroups:
  - nwctl.hrk091.dev
  resources:
  - devicerollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nwctl.hrk091.dev
  resources:
  - devicerollouts/status
  verbs:
  - get
