apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nwctl-aggregator.deploy.yaml
- nwctl-aggregator.svc.yaml
- nwctl-aggregator.pvc.yaml
- nwctl-server.deploy.yaml
- nwctl-server.svc.yaml
- nwctl-server.pvc.yaml

images:
- name: nwctl
  newName: nwctl
  newTag: latest
