apiVersion: v1
kind: Service
metadata:
  name: nwctl-aggregator
spec:
  type: ClusterIP
  selector:
    app: nwctl-aggregator
  ports:
    - name: grpc
      port: 9339
      targetPort: 9339
      protocol: TCP
