# permissions for end users to view ocdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocdemo-viewer-role
rules:
- apiGroups:
  - nwctl.hrk091.dev
  resources:
  - ocdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nwctl.hrk091.dev
  resources:
  - ocdemoes/status
  verbs:
  - get
