apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-operator-controller-manager
  namespace: device-operator-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: NWCTL_AGGREGATOR_URL
              value: http://kuesta-aggregator.kuesta-system:8000
            - name: NWCTL_SUBSCRIBER_IMAGE
              value: device-subscriber
