apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwctl-aggregator
spec:
  template:
    spec:
      containers:
        - name: nwctl
          env:
            - name: NWCTL_STATUS_REPO_URL
              value: https://github.com/nwctl-example/nwctl-status
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwctl-server
spec:
  template:
    spec:
      containers:
        - name: nwctl
          env:
            - name: NWCTL_CONFIG_REPO_URL
              value: https://github.com/nwctl-example/nwctl-config
            - name: NWCTL_STATUS_REPO_URL
              value: https://github.com/nwctl-example/nwctl-status
