apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwctl-aggregator
spec:
  template:
    spec:
      containers:
        - name: nwctl
          env:
            - name: NWCTL_GIT_REPO_URL
              value: https://github.com/hrk091/nwctl-testdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwctl-server
spec:
  template:
    spec:
      containers:
        - name: nwctl
          env:
            - name: NWCTL_GIT_REPO_URL
              value: https://github.com/hrk091/nwctl-testdata
